Adapt artifact upload to deprecation of `actions/upload-artifact@v2`
Use `actions/upload-artifact@v4` to avoid running into the following error:

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```